//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesDataAccessLayes.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMovieActor
    {
        public int ID { get; set; }
        public int MovieID { get; set; }
        public int ActorID { get; set; }
    
        public virtual tblFilmCrew tblFilmCrew { get; set; }
        public virtual tblMovy tblMovy { get; set; }
    }
}
